### ISSUE TITLE
Editor would crash moments after open - InvalidSchema error

### ISSUE THREAD

**Issue by igalst** [wix-incubator/corvid#158]
Freshlly cloned site would crash moments after opening the Editor due to `InvalidSchema` exception.

**To Reproduce**
1. `npx create-corvid-app MY_PROJECT https://www.MY_SITE.com/`
2. `cd ./MY_PROJECT`
3. `npx corvid open-editor`
4. Console output: 
```
Corvid Technical Preview
Find out more about Corvid at www.wix.com/corvid
The Corvid CLI is used for working with local versions of your Wix sites. Using the CLI you can create new local projects, open a local editor, and pull project updates.
✔ Editor connected

[corvid] an error has occured. see [.corvid/session.log] for details.
```
**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - node 10.17.0

**Additional context**
`session.log` file:
```
{"message":"Server starting at /Users/igalst/Projects/MY_PROJECT","level"{"message":" {\"message\":\"com.wixpress.cloud.data.core.domain.schema.InvalidSchema: Invalid schema\",\"stack\":\"Error: com.wixpress.cloud.data.core.domain.schema.InvalidSchema: Invalid schema\\n    at fetchJson (wix/node_modules/@wix/cloud-data-schemas-client/src/utils/http.js:40:25)\"}","level":"error","stack":"Error:  {\"message\":\"com.wixpress.cloud.data.core.domain.schema.InvalidSchema: Invalid schema\",\"stack\":\"Error: com.wixpress.cloud.data.core.domain.schema.InvalidSchema: Invalid schema\\n    at fetchJson (wix/node_modules/@wix/cloud-data-schemas-client/src/utils/http.js:40:25)\"}\n    at Object.error (/Users/igalst/Projects/MY_PROJECT/node_modules/corvid-cli/src/commands/open-editor.js:127:20)\n    at Socket.<anonymous> (/Users/igalst/Projects/MY_PROJECT/node_modules/corvid-cli/src/utils/electron.js:61:37)\n    at Socket.emit (events.js:198:13)\n    at Socket.EventEmitter.emit (domain.js:448:20)\n    at addChunk (_stream_readable.js:287:12)\n    at readableAddChunk (_stream_readable.js:268:11)\n    at Socket.Readable.push (_stream_readable.js:223:10)\n    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","timestamp":"2019-11-07T06:17:19.483Z"}
t GET_DOCUMENT received","level":"info","timestamp":"2019-11-07T06:17:08.721Z"}
{"message":"Site document requested","level":"verbose","timestamp":"2019-11-07T06:17:08.721Z"}
{"message":"Socket event IS_CLONE_MODE received","level":"info","timestamp":"2019-11-07T06:17:16.090Z"}
{"message":"Socket event GET_CODE received","level":"info","timestamp":"2019-11-07T06:17:16.201Z"}
{"message":"code files requested","level":"verbose","timestamp":"2019-11-07T06:17:16.201Z"}
{"message":" {\"message\":\"com.wixpress.cloud.data.core.domain.schema.InvalidSchema: Invalid schema\",\"stack\":\"Error: com.wixpress.cloud.data.core.domain.schema.InvalidSchema: Invalid schema\\n    at fetchJson (wix/node_modules/@wix/cloud-data-schemas-client/src/utils/http.js:40:25)\"}","level":"error","userMessage":"There was an error initializing your site. Please try again.","stack":"EditorError:  {\"message\":\"com.wixpress.cloud.data.core.domain.schema.InvalidSchema: Invalid schema\",\"stack\":\"Error: com.wixpress.cloud.data.core.domain.schema.InvalidSchema: Invalid schema\\n    at fetchJson (wix/node_modules/@wix/cloud-data-schemas-client/src/utils/http.js:40:25)\"}\n    at [CORVID] (/Users/igalst/Projects/MY_PROJECT/node_modules/corvid-cli/src/apps/open-editor.js:59:15)\n    at WebContents.<anonymous> (/Users/igalst/Projects/MY_PROJECT/node_modules/corvid-cli/src/utils/clientMessageActions.js:9:9)\n    at WebContents.emit (events.js:194:13)\n    at WebContents.EventEmitter.emit (domain.js:469:20)\n    at WebContents.topLevelDomainCallback (domain.js:124:23)","timestamp":"2019-11-07T06:17:19.483Z"}
{"message":"Server closing","level":"info","timestamp":"2019-11-07T06:17:20.941Z"}
{"message":"Editor disconnected","level":"verbose","timestamp":"2019-11-07T06:17:20.947Z"}
{"message":"Admin disconnected","level":"verbose","timestamp":"2019-11-07T06:17:20.948Z"}
```

**Comment by tomenden** [comment]
Hi @igalst ,

Thanks for reporting!
There seems to be some issue related to a specific collection on your site. We've seen a few other occurrences of this issue in other sites. I sent it over to the WixData team for investigation, I will keep you posted.

**Comment by tomenden** [comment]
Issue should be resolved now.
@igalst can you please confirm?

**Comment by igalst** [comment]
@tomenden thanks, seems to be resolved.
