### ISSUE TITLE
Editor crashes after open

### ISSUE THREAD

**Issue by igalst** [wix-incubator/corvid#170]
**Describe the bug**
The Editor crashes shortly after opening.

**To Reproduce**
```
➜  git:(master) ✗ npx corvid open-editor
Corvid Technical Preview
Find out more about Corvid at www.wix.com/corvid
The Corvid CLI is used for working with local versions of your Wix sites. Using the CLI you can create new local projects, open a local editor, and pull project updates.
✔ Editor connected

[corvid] an error has occured. see [.corvid/session.log] for details.
```

**session.log**
```
{"message":"Server starting at /Users/igalst/Projects/FOLDER","level"{"message":" {\"message\":\"Invalid file content\",\"stack\":\"Error: Invalid file content\\n    at Object.writeFile (https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:244166)\\n    at E (https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:946343)\\n    at https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:946446\\n    at Array.map (<anonymous>)\\n    at I (https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:946397)\\n    at https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:947368\"}","level":"error","stack":"Error:  {\"message\":\"Invalid file content\",\"stack\":\"Error: Invalid file content\\n    at Object.writeFile (https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:244166)\\n    at E (https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:946343)\\n    at https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:946446\\n    at Array.map (<anonymous>)\\n    at I (https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:946397)\\n    at https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:947368\"}\n    at Object.error (/Users/igalst/Projects/FOLDER/node_modules/corvid-cli/src/commands/open-editor.js:101:20)\n    at Socket.<anonymous> (/Users/igalst/Projects/FOLDER/node_modules/corvid-cli/src/utils/electron.js:69:37)\n    at Socket.emit (events.js:198:13)\n    at Socket.EventEmitter.emit (domain.js:448:20)\n    at addChunk (_stream_readable.js:287:12)\n    at readableAddChunk (_stream_readable.js:268:11)\n    at Socket.Readable.push (_stream_readable.js:223:10)\n    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","timestamp":"2019-11-26T10:56:33.143Z"}
"2019-11-26T10:56:29.437Z"}
{"message":"getCodeFiles finished","level":"info","timestamp":"2019-11-26T10:56:29.501Z"}
{"message":"Socket event GET_CODE handled succesfully","level":"info","timestamp":"2019-11-26T10:56:29.510Z"}
{"origin":"unhandledRejection","message":" {\"message\":\"Invalid file content\",\"stack\":\"Error: Invalid file content\\n    at Object.writeFile (https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:244166)\\n    at E (https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:946343)\\n    at https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:946446\\n    at Array.map (<anonymous>)\\n    at I (https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:946397)\\n    at https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:947368\"}","level":"error","userMessage":"There was an error initializing your site. Please try again.","stack":"EditorError:  {\"message\":\"Invalid file content\",\"stack\":\"Error: Invalid file content\\n    at Object.writeFile (https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:244166)\\n    at E (https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:946343)\\n    at https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:946446\\n    at Array.map (<anonymous>)\\n    at I (https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:946397)\\n    at https://static.parastorage.com/unpkg/document-services-implementation@1.502.0/dist/document-services-implementation.js:1:947368\"}\n    at [CORVID] (/Users/igalst/Projects/FOLDER/node_modules/corvid-cli/src/apps/open-editor.js:59:15)\n    at WebContents.<anonymous> (/Users/igalst/Projects/FOLDER/node_modules/corvid-cli/src/utils/clientMessageActions.js:9:9)\n    at WebContents.emit (events.js:194:13)\n    at WebContents.EventEmitter.emit (domain.js:469:20)\n    at WebContents.topLevelDomainCallback (domain.js:124:23)","timestamp":"2019-11-26T10:56:33.143Z"}
{"message":"Server closing","level":"info","timestamp":"2019-11-26T10:56:34.928Z"}
{"message":"Editor disconnected","level":"verbose","timestamp":"2019-11-26T10:56:34.929Z"}
{"message":"Admin disconnected","level":"verbose","timestamp":"2019-11-26T10:56:34.933Z"}
{"message":"deleteOrphanFiles started","level":"info","timestamp":"2019-11-26T10:56:34.933Z"}
{"message":"deleteOrphanFiles finished","level":"info","timestamp":"2019-11-26T10:56:34.973Z"}

```

**Comment by tomenden** [comment]
Hi @igalst ,
Per the error message, it seems like one of the files is corrupted in some way. Can you please share your site and a git repo containing the files that you're experiencing this with so we can find the culprit? (Feel free to share it with me privately if you don't want to share it with the world)

Fyi - we are currently working on giving better indications for these kind of errors, which will hopefully allow you to understand which file causes the problem, and how to fix it.
Cc @kostagersh

**Comment by igalst** [comment]
Thanks @tomenden. I've emailed you additional details privately.

**Comment by kostagersh** [comment]
Hi @igalst ,
I've investigated the problem and the root of it is 3 pairs of collections different only by case: Bases - bases, Regions - regions and Countries - countries. We're looking into it.

**Comment by igalst** [comment]
Thanks for the update @kostagersh.
Indeed, while we're refactoring the site there are multiple sets of collections with same naming but different case. Wix Collections are considered case sensitive, so I didn't think that would cause any issue. At least, at the regular Editor it works perfect. 

Looking forward for your next update.

**Comment by igalst** [comment]
@kostagersh ,  could you please share status?

**Comment by kostagersh** [comment]
Not fixed yet, will work on it soon.
